import React from 'react'
import './Policy.Styles.scss'
import ContactUsSection from '../../Components/ContactUsSection/ContactUsSection'

const TandC = () => {
  return (
    <div className='policy-page'>
      <h1 className='title'>TERMS OF USE</h1>
      <div className='text'>
        <p>
          This document (“<strong>Terms</strong>”) is an electronic record in terms of
          the Information Technology Act, 2000 and rules there under as applicable and
          the amended provisions pertaining to electronic records in various statutes as
          amended by the Information Technology Act, 2000. This electronic record is
          generated by a computer system and does not require any physical or digital
          signatures.
        </p>
        <p>Welcome to the RiceHouse Wholesale and Retail Platform.</p>
        <p>
          This document is a legally binding agreement between RiceHouse, a company 
          incorporated under the Companies Act, 2013 with its
          registered office at 12/2-66, Krishanappa layout, R. R. Nagar, Kerekodi Main 
          Rd, Hosakerehalli, Bengaluru, Karnataka 560085, India (including its
          subsidiaries, group companies , and affiliates, as may also be referred to as
          “<strong>we</strong>”, “<strong>us</strong>”, “<strong>our</strong>” or
          “<strong>RiceHouse</strong>” hereinafter, as the context requires) and Buyer
          <em>(as defined below)</em> (acting by itself or through its representatives,
          as the case may be, referred to as <strong>“you”</strong>,
          <strong>“your”</strong>, <strong>“User”, “Buyer” </strong>hereinafter) who
          accesses or uses or transacts on [www.ricehouse.in] website and
          <strong>RiceHouse</strong> mobile application ( “<strong>Platform</strong>”) and
          purchases Products for business to business (“<strong>B2B</strong>”)
          commercial purposes only.
        </p>
        <p>
          By accessing or signing up to the Platform and/or Services (as defined below),
          you agree to be bound by these Terms, any additional terms (including
          pertaining to specific offers, promotions, discounts, etc), conditions,
          guidelines and rules that we provide to you, including in connection with your
          use of the Services that we may offer or make available to you, other rules
          and policies of the Platform as may be amended, modified or replaced
          from time to time. Please read them carefully.
        </p>
        <p>
          We retain an unconditional right to modify or amend the Platform Policies. We,
          at any time, have the right to add to and/or alter, modify, change or vary all
          or any of the Terms or to replace wholly or in part, the contests, offers,
          schemes, promotions etc. with another contest, offer, scheme, promotion etc.
          or to withdraw it altogether.&nbsp; User can access
          the latest version of these Terms at any given time on our Platform. User
          should regularly review the Terms on the Platform. User's continued use of and
          access to the Platform shall be User's consent to such changes. In the event
          the modified Terms are not acceptable to User, User should discontinue
          accessing the Platform.
        </p>
        <p>
          PLEASE READ THE TERMS CAREFULLY BEFORE PROCEEDING IF YOU DO NOT AGREE TO ALL
          OF THESE TERMS, DO NOT ACCESS OR USE THE PLATFORM OR THE SERVICES PROVIDED BY
          THE PLATFORM OR RiceHouse.
        </p>
        <ol>
          <li><strong>DEFINITIONS</strong></li>
        </ol>
        <p>
          For the purposes of this document, the following capitalised terms shall have
          the following meaning:
        </p>
        <ol type="I">
          <li>
            “<strong>Applicable Law(s)</strong>” shall mean any statute, national,
            state, provincial, local, municipal, foreign, international, multinational
            or other law, treaty, code, enactment, regulation, ordinance, rule,
            judgment, notification, direction, order, decree, bye-law, approval of any
            Governmental Authority, directive, guideline, policy, requirement or other
            governmental restriction or any similar form of decision of or determination
            by, or any interpretation or administration having the force of law of any
            of the foregoing by any Governmental Authority having jurisdiction over the
            matter in question, whether in effect as of the date of this Terms or at any
            time thereafter.
          </li>
          <li>
            “<strong>Business Day</strong>” shall mean Monday to Saturday, 10:00 am to
            07:00 pm and shall not include such days on which the banking institutions
            in India are authorized or obligated under the Applicable Laws to remain
            closed;
          </li>
          <li>
            “<strong>Buyer</strong>”&nbsp;shall mean business users, holding valid and
            current business registration documentation, including but not limited to a
            Goods and Services Tax (GST) registration certificate, trade license, and/or
            any other legally recognized business identification document, as required
            under Applicable Laws, who access, use, or transact on the Platform, avail
            Services or purchase Products from it solely on a business to business
            (“<strong>B2B</strong>”) basis for commercial purposes and not for personal
            consumption.
          </li>
          <li>
            “<strong>Consignee</strong>”&nbsp;shall mean the Buyer or any person named
            in the Delivery Note or his/her representatives that takes the delivery of
            Shipment being transported.
          </li>
          <li>
            “<strong>Dangerous Goods</strong>”&nbsp;includes products that are or may
            become dangerous, hazardous, inflammable, radioactive, or of damaging nature
            including products liable to taint or affect other products and products
            likely to harbor or encourage vermin or other pests; provided however that,
            household insecticide products shall not constitute Dangerous Goods.
          </li>
          <li>
            “<strong>Delivery Note</strong>”&nbsp;shall mean the waybill containing the
            essential information (as determined by us on our sole discretion) required
            for the performance of the logistics services, including name, delivery
            address and contact number of the Buyer or the designated recipient of the
            Shipment, description of the contents of the Shipment (if applicable) and
            Cash on Delivery details (if applicable).
          </li>
          <li>
            “<strong>Governmental Authority</strong>” shall mean any:
            <ol type="i">
              <li>
                government (central, federal, state or otherwise) or sovereign state;
              </li>
              <li>
                any regulatory bodies, including the RBI and the Securities and Exchange
                Board of India;
              </li>
              <li>
                any governmental agency, semi-governmental or judicial or quasi-judicial
                or administrative entity, department or authority, or any political
                subdivision thereof; or
              </li>
              <li>international organization, agency or authority,</li>
              <li>
                including, without limitation, any stock exchange or any self-regulatory
                organization, established under any Applicable Law (to the extent acting
                in its capacity as a government entity and not as a contracting or
                private party);
              </li>
            </ol>
          </li>
          <li>
            “<strong>including</strong>” herein shall always mean “including, without
            limitation”.
          </li>
          <li>
            “<strong>Order(s)</strong>”&nbsp;shall mean order placed by Buyer for
            purchasing Products / Services on the Platform.
          </li>
          <li>
            “<strong>Order Detail(s)</strong>”&nbsp;shall mean the details relating to
            the Order, including without limitation, the description of Products,
            details of RiceHouse and the Buyer, date of order placement, total amount
            payable by the Buyer, delivery date, mode of payment, unique order number
            (AWB number) etc.
          </li>
          <li>
            “<strong>Platform Content</strong>” shall mean any information, text,
            images, graphics, video clips, sound, directories, files, databases or
            listings, etc. available on or through the Platform;
          </li>
          <li>
            “<strong>Product(s)</strong>”&nbsp;shall mean goods of any categories (other
            than Dangerous Goods).
          </li>
          <li>
            “<strong>Services</strong>” shall mean services to enable cash and carry
            wholesale trading as provided through the Platform including:
            <ol type="i">
              <li>enabling Buyers to discover Products and order them;</li>
              <li>sale of Products to Buyers;</li>
              <li>
                tracking Shipments, Products and other logistics services provided by us
                or our sub-contractors;
              </li>
              <li>
                processing payments (including payment which are processed through
                integrated third-party service providers);
              </li>
              <li>
                offering credit and financing solutions in relation to Products; and/or
              </li>
              <li>
                any additional services provided, offered or introduced by us to enhance
                business transactions on the Platform.
              </li>
            </ol>
          </li>
          <li>
            “<strong>Shipment(s) / Consignment(s)</strong>”&nbsp;means all Products
            (excluding documents) that travel under one Delivery Note and which may be
            carried by any means we choose in our discretion, including air, road or any
            other carrier.
          </li>
          <li>
            “<strong>User Content</strong>” shall mean any information, content or
            material of the Buyer that is on the Platform.
          </li>
        </ol>
        <br />
        <ol start="2">
          <li><strong>EFFECTIVE DATE</strong></li>
        </ol>
        <p>
          These Terms of Use shall come into force with effect from 0000 hours of 7<sup>th</sup>
          April 2025.
        </p>
        <br />
        <ol start="3">
          <li><strong>ELIGIBILITY </strong></li>
        </ol>
        <p>
          Your acceptance of these Terms implies that you have the capacity to enter
          into a legally binding contract as per the Indian Contract Act, 1872. Persons
          who are “incompetent to contract” within the meaning of the Indian Contract
          Act, 1872 including without limitation, minors, un-discharged insolvents, etc.
          are not eligible to use the Platform. For the purposes of these Terms, the
          term ‘persons' shall mean any sole proprietor, firm, company,
          corporation, government, state or agency of a state or any association, trust,
          joint venture, consortium or partnership (whether or not having separate legal
          personality) or any other body corporate duly incorporated under the laws of
          India.
        </p>
        <br />
        <ol start="4">
          <li>
            <strong>PROVISION OF SERVICES</strong>
            <ol type="I">
              <li>
                You must register on the Platform in order to access and use the
                Services. Further, RiceHouse reserves the right, without prior notice, to
                restrict access to or use of certain Services (or any features within
                the Services) subject to other conditions that RiceHouse may impose in its
                discretion.&nbsp;
              </li>
              <li>
                In case you avail services while accessing the Platform, that may be
                supported and/or provided by third party service provider(s), for all
                such services your contracting entity will be such third-party service
                provider(s), as the case may be. RiceHouse disclaims all liability for any
                claims that may arise pursuant to your use of services provided by such
                third-party service provider(s).
              </li>
              <li>
                User agrees and confirms that RiceHouse may charge commissions, transaction
                fees, or other charges for the use of certain features on the Platform.
                Any applicable fees will be communicated to Users in advance.
              </li>
              <li>
                User agrees and confirms that any Products/Services provided to User by
                RiceHouse are on best efforts basis and RiceHouse may engage services of
                third-party service provider(s) to facilitate such Services to User. We
                shall not in any manner be liable to you for failure or delay in
                providing the Services or for any temporary disablement, permanent
                discontinuance of the Services by us or for any consequences resulting
                from such actions or reasons that are beyond our reasonable control.
              </li>
              <li>
                User agrees and confirms that it will comply with Applicable Laws and
                RiceHouse's Policies while availing the Services. RiceHouse may suspend or
                terminate User's access for any violations, fraudulent activities, or
                misuse of the Platform.
              </li>
              <li>
                User acknowledges that the Services are being provided to you on a
                ‘as is' and ‘as available' basis and may be interrupted
                while browsing, transacting, using or uploading information on the
                Platform. User agrees that we reserve the right to suspend the Services,
                forthwith without assigning any reason whatsoever, at our sole
                discretion.
              </li>
              <li>
                RiceHouse may at any time with or without notice, withdraw, terminate,
                and/or suspend any or part of the Services without cause or in case of
                any breach of the Terms by the User. In addition, termination of any or
                part of any Services shall not impact provision of other services or
                other business arrangements or agreements which the User may have
                entered into with RiceHouse.
              </li>
            </ol>
          </li>
          <br />
          <li>
            <strong>USER ACCOUNTS AND VERIFICATION OF ACCOUNT</strong>
            <ol type="I">
              <li>
                You must be registered on the Platform to access or avail the Products
                and Services. While registering the User account on the Platform you
                will be required to furnish details about you and with respect to your
                business including without limitation, business name, GSTIN, PAN, TAN,
                Udyog Aadhaar, address, phone number, geographical location, image of
                the place of business and/ or any other information that RiceHouse may
                require you to provide.
              </li>
              <li>
                You agree and acknowledge that you will transact on the Platform only
                for your business purposes that is for purchase of Products for further
                distribution or sale and not for personal use or consumption. Except
                with RiceHouse's approval, one User may only register one account on the
                Platform. RiceHouse may cancel or terminate an User's account if RiceHouse has
                reasons to suspect that the User has concurrently registered or is
                controlling two or more accounts. Further, RiceHouse may reject User's
                application for registration for any other reason whatsoever, without
                assigning any reasons to the User.
              </li>
              <li>
                A set of User ID and OTP (One Time Password) / password is unique to a
                single account. Any action triggered on your User account on the
                Platform or by using the unique OTP will be deemed to have been
                authorised by you and with your express consent. You shall be solely
                responsible for maintaining the confidentiality and security of your
                User ID and password and for all activities that occur under your
                account. You agree that all activities that occur under your account
                (including without limitation, posting any company or product
                information, clicking to accept any terms &amp; conditions or rules,
                subscribing to or making any payment for any Services, sending emails
                using the Platform or other communications) will be deemed to have been
                authorized by you.
              </li>
              <li>
                You acknowledge that it is your responsibility to maintain the
                confidentiality of your account credentials and all activities occurring
                under your account.
              </li>
              <li>
                RiceHouse reserves the right to verify, approve, suspend, or reject any
                account at its discretion, including requesting additional information /
                documents for verification.
              </li>
              <li>
                When you access the Platform, you are electronically communicating with
                RiceHouse. RiceHouse may communicate with you by e-mail, SMS, WhatsApp messages
                or messages through other modes of communication, phone call or by
                posting notices on the Platform or by sending in-app notifications or
                any other mode of communication. For contractual purposes, you consent
                to receive communications (including transactional, promotional and/or
                commercial messages) in the above manner, from RiceHouse with
                respect&nbsp;to your use of the Platform and it shall be deemed by your
                continued use of the Platform that you agree and consent to receive any
                communications from RiceHouse.&nbsp;
              </li>
              <li>
                You agree and acknowledge that we may directly or through a third-party
                service provider in accordance with the terms of the Privacy Policy
                validate the information provided by you on the Platform. You agree to
                furnish additional information and provide documentary proof as may be
                requested by us, from time to time, for the purposes of verification of
                your User account information. If any information provided by you is
                found to be incorrect or misleading, RiceHouse reserves its right to take
                appropriate steps as set forth under Paragraph 5 of these Terms. For the
                purposes of verification of your account information, you agree that we
                may share your information with such third-party service provider in
                accordance with the terms of the Privacy Policy.
              </li>
            </ol>
          </li>
          <br />
          <li>
            <strong>OBLIGATIONS OF USERS </strong>
            <ol type="I">
              <li>
                You agree that (a) you will not copy, reproduce, download, re-publish,
                sell, distribute or resell any Platform Content, and (b) you will not
                copy, reproduce, download, compile or otherwise use any Platform Content
                for the purposes of operating a business that competes with RiceHouse, or
                otherwise commercially exploiting the Platform Content or systematic
                retrieval of Platform Content from the Platform to create or compile,
                directly or indirectly, a collection, compilation, database or directory
                (whether through deep-link, page scrape, robots, spiders, automatic
                devices or manual processes).
              </li>
              <li>
                RiceHouse may allow Users access to content, products or services offered by
                third parties through hyperlinks (in the form of word link, banners,
                channels or otherwise), API or otherwise to such third parties' web
                sites. You are cautioned to read such third party's terms and conditions
                and/or privacy policies before using the Platform with respect to such
                content, products or services that you may avail. You acknowledge that
                RiceHouse has no control over such third parties' websites and shall not be
                responsible or liable to anyone for such websites, or any content,
                products or services made available on such websites.
              </li>
              <li>
                You agree not to undertake any action which may undermine the integrity
                of RiceHouse's feedback system.
              </li>
              <li>
                By posting or displaying User Content on the Platform or providing any
                User Content to RiceHouse or our representative(s), you grant perpetual,
                worldwide, royalty-free, and sub-licensable license to RiceHouse to display,
                transmit, distribute, reproduce, publish, translate, and otherwise use
                any or all of the User Content in any form, media, or technology now
                known or not currently known in any manner and for any purpose which may
                be beneficial to the operation of the Platform, the provision of any
                Services and/or the business of the User. You confirm and warrant to
                RiceHouse that you have all the rights, power and authority necessary to
                grant the above license.
              </li>
              <li>
                User agrees, undertakes, and confirms that User's use of Platform shall
                be strictly governed by the following binding principles:
                <ol type="i">
                  <li>
                    User shall not host, display, upload, modify, publish, transmit,
                    store, update or share any information which:
                    <ol type="a">
                      <li>
                        belongs to another person and to which User does not have any
                        right to;
                      </li>
                      <li>
                        is grossly harmful, harassing, blasphemous, defamatory, obscene,
                        pornographic, pedophilic, libelous, invasive of another's
                        privacy including bodily privacy, hateful, racially or
                        ethnically objectionable, disparaging, relating or encouraging
                        money laundering or gambling, or otherwise unlawful in any
                        manner whatever; or unlawfully threatening or unlawfully
                        harassing including but not limited to “indecent representation
                        of women” within the meaning of the Indecent Representation of
                        Women (Prohibition) Act, 1986 or otherwise inconsistent with or
                        contrary to the laws in force;
                      </li>
                      <li>is misleading in any way;</li>
                      <li>
                        is patently offensive to the online community, such as sexually
                        explicit content, or content that promotes obscenity,
                        pedophilia, racism, bigotry, hatred or physical harm of any kind
                        against any group or individual;
                      </li>
                      <li>harasses or advocates harassment of another person;</li>
                      <li>
                        involves the transmission of “junk mail”, “chain letters”, or
                        unsolicited mass mailing or “spamming” or messages using RiceHouse's
                        communication Platform;
                      </li>
                      <li>
                        promotes illegal activities or conduct that is abusive,
                        threatening, obscene, defamatory or libelous;
                      </li>
                      <li>
                        infringes upon or violates any third party's rights including,
                        but not limited to, intellectual property rights, rights of
                        privacy (including without limitation unauthorized disclosure of
                        a person's name, email address, physical address or phone
                        number) or rights of publicity;
                      </li>
                      <li>
                        promotes an illegal or unauthorized copy of another person's
                        copyrighted work, such as providing pirated computer programs or
                        links to them, providing information to circumvent
                        manufacture-installed copy-protect devices, or providing pirated
                        music or links to pirated music files;
                      </li>
                      <li>
                        contains restricted or password-only access pages, or hidden
                        pages or images (those not linked to or from another accessible
                        page);
                      </li>
                      <li>
                        provides material that exploits people in a sexual, violent or
                        otherwise inappropriate manner or solicits personal information
                        from anyone;
                      </li>
                      <li>
                        provides instructional information about illegal activities such
                        as making or buying illegal weapons, violating someone's
                        privacy, or providing or creating computer viruses;
                      </li>
                      <li>
                        contains video, photographs, or images of another person (with a
                        minor or an adult);
                      </li>
                      <li>
                        engages in commercial activities and/or sales without prior
                        written consent such as contests, sweepstakes, barter,
                        advertising and pyramid schemes, or the buying or selling of
                        “virtual” products related to the Platform. Throughout this
                        Terms, RiceHouse's prior written consent means a communication
                        coming from RiceHouse's Legal Department, specifically in response
                        to your request, and specifically addressing the activity or
                        conduct for which you seek authorization;
                      </li>
                      <li>
                        solicits gambling or engages in any gambling activity which, in
                        sole discretion, believes is or could be construed as being
                        illegal;
                      </li>
                      <li>
                        interferes with another user's use and enjoyment of the Platform
                        or enjoyment of any similar Services;
                      </li>
                      <li>
                        refers to any website or URL that, in sole discretion, contains
                        material that is inappropriate for the Platform or any other
                        website, contains content that would be prohibited or violates
                        the letter or spirit of these Terms;
                      </li>
                      <li>harm minors in any way;</li>
                      <li>
                        infringes any patent, trademark, copyright or other proprietary
                        rights or third party's trade secrets or rights of publicity or
                        privacy or shall not be fraudulent or involve the sale of
                        counterfeit or stolen products;
                      </li>
                      <li>violates any law for the time being in force;</li>
                      <li>
                        deceives or misleads the addressee/ users about the origin of
                        such messages or communicates any information which is grossly
                        offensive or menacing in nature or knowingly and intentionally
                        communicates any information which is patently false or
                        misleading in nature but may reasonably be perceived as a fact;
                      </li>
                      <li>impersonate another person;</li>
                      <li>
                        contains software viruses or any other computer code, files or
                        programs designed to interrupt, destroy or limit the
                        functionality of any computer resource; or contains any trojan
                        horses, worms, time bombs, cancel-bots, easter eggs or other
                        computer programming routines that may damage, detrimentally
                        interfere with, diminish value of, surreptitiously intercept or
                        expropriate any system, data or personal information;
                      </li>
                      <li>
                        threatens the unity, integrity, defence, security or sovereignty
                        of India, friendly relations with foreign states, or public
                        order or causes incitement to the commission of any cognizable
                        offence or prevents investigation of any offence or is insulting
                        any other nation;
                      </li>
                      <li>
                        directly or indirectly, offers, attempts to offer, trade or
                        attempt to trade in any item, the dealing of which is prohibited
                        or restricted in any manner under the provisions of any
                        applicable law, rule, regulation or guideline for the time being
                        in force;
                      </li>
                      <li>
                        create liability for RiceHouse or cause RiceHouse to lose (in whole or
                        in part) the Services of our internet service provider (“ISPs”)
                        or other suppliers;
                      </li>
                      <li>
                        is patently false and untrue, and is written or published in any
                        form, with the intent to mislead or harass a person, entity or
                        agency for financial gain or to cause any injury to any person.
                      </li>
                    </ol>
                  </li>

                  <li>
                    User shall not make any defamatory or denigrating statement(s) about
                    RiceHouse, or our brand name or domain name used by RiceHouse including the
                    terms [RiceHouse, , RiceHouse.com, and RiceHousepay] or otherwise act in any
                    manner that might tarnish the reputation or standing, of RiceHouse or
                    Users on the Platform or otherwise tarnish or dilute any of RiceHouse's
                    trademarks, service marks, trading name, or the goodwill associated
                    with them.
                  </li>

                  <li>
                    User shall at all times ensure full compliance with Applicable Laws.
                  </li>
                  <li>
                    User shall not attempt to gain unauthorized access to any portion or
                    feature of the Platform (such as profiles, blogs, communities,
                    account information, bulletins, friend request etc.), or any other
                    systems or networks connected to the Platform or to any server,
                    computer, network, or to any of the Services offered on or through
                    the Platform, by hacking, password “mining” or any other
                    illegitimate means.
                  </li>
                  <li>
                    Unless expressly permitted, User shall not probe, scan or test the
                    vulnerability of the Platform or any network connected to the
                    Platform nor breach the security or authentication measures on the
                    Platform, or any network connected to the Platform. User shall not
                    reverse look-up, trace or seek to trace any information on any other
                    User of or visitor to Platform, or any other User, including any
                    account on the Platform not owned by User, to its source, or exploit
                    the Platform or any service or information made available or offered
                    by or through the Platform, in any way where the purpose is to
                    reveal any information, including but not limited to personal
                    identification or information, other than User's own information, as
                    provided for by the Platform.
                  </li>
                  <li>
                    You agree to indemnify RiceHouse, its affiliates, directors, employees,
                    agents and representatives and to hold them harmless, from any and
                    all damages, losses, claims and liabilities (including legal costs
                    on a full indemnity basis) which may arise from or in connection
                    with: (i) your submission, posting or display of any User Content;
                    (ii) from your use of the Platform or Services; (iii) from your
                    breach of the Terms or breach of any Applicable Laws, including tax
                    laws; (iv) any service availed by you from a third party service
                    provider using any dispute inter-se&nbsp;Users; and/or (vi) your
                    negligence or willful misconduct.
                  </li>
                  <li>
                    User should ensure that:
                    <ol type="a">
                      <li>
                        You and your employees, sub-contractors, service providers,
                        etc., shall comply with all applicable modern slavery and human
                        trafficking laws in force;
                      </li>
                      <li>
                        you do not, whether directly or indirectly, use any
                        forced/bonded labor or human trafficking in your organization
                        and you do not require your employees, contractors, etc., to
                        maintain monetary deposits or safekeep any identity documents as
                        terms of their service with you;
                      </li>
                      <li>
                        you do not employ whether directly or indirectly, any child
                        labor and all your employees are above the minimum legal age;
                      </li>
                      <li>
                        your employees are provided fair wages and are provided fair
                        working conditions;
                      </li>
                      <li>
                        you are an equal opportunity employer and do not discriminate on
                        grounds of gender, race, religion, caste, or any other socio-
                        economic background;
                      </li>
                      <li>
                        you respect the employees' right to freedom of association;
                      </li>
                      <li>
                        your employees have the right to leave the employment and are
                        not continuing with the employment under coercion or duress; and
                      </li>
                      <li>
                        your employees have adequate grievance redressal mechanism to
                        raise any concerns related to modern slavery.
                      </li>
                    </ol>
                  </li>
                </ol>
              </li>
            </ol>
          </li>
          <br />
        </ol>
        <ol start="7">
          <li>
            <strong>TRANSACTIONS BETWEEN RiceHouse AND BUYER </strong>
            <ol type="I">
              <li>
                [All Products and Services listed on the Platform will be sold
                exclusively by RiceHouse, and RiceHouse will have sole control over any
                advertisements, exhibitions, offers, or transactions related to the sale
                or purchase of Products and Services on the Platform.]
              </li>
              <li>
                Upon delivery of the Products, the risk in the Products shall pass to
                the Buyer. However, the title of Products shall remain with RiceHouse until
                payment for the Products is made. It is hereby clarified that RiceHouse
                shall have no liability or responsibility of any nature whatsoever
                towards any kind of loss or damage to the Products suffered by you.
                Buyer acknowledges and undertakes that it is transacting on the Platform
                at its own risk and is using its best and prudent judgment before
                entering into any transactions through the Platform.
              </li>
              <li>
                Buyer shall ensure that any Product returned shall be returned in
                accordance with the '<a href="https://ricehouse.in/returnpolicy">Return Shipment Policy</a>'.
              </li>
              <li>
                All orders placed by the Buyer on the Platform will be deemed as a valid
                Order by you and RiceHouse will, notify through the Platform, the acceptance
                or non-acceptance of such Order within the timeline solely determined by
                RiceHouse. Upon acceptance, each Order will be a separate and distinct
                contract for the sale and purchase of Products between the Buyer and
                RiceHouse. The Buyer will not be entitled to make any changes in the Order
                once it is accepted by us.
              </li>
              <li>
                We reserve the right, at our sole discretion, to refuse or cancel any
                Order for any reason whatsoever before delivering the Products to you.
                You can cancel the Order any time before we accept your Order.
              </li>
              <li>
                The Products shall be sold by RiceHouse and purchased by Buyer at the price
                agreed upon at the time of placing of an Order. Price mentioned on the
                invoice issued by RiceHouse to you shall be final and binding and shall
                include all taxes, levies, duties and other charges including Goods and
                Services Taxes (GST) and other local levies prevailing at the time of
                delivery and shall be charged to your account.
              </li>
              <li>
                We shall be solely responsible for raising invoices directly to the
                Buyer for Products sold by
              </li>
              <li>
                Buyer agrees that RiceHouse shall not be liable for any damages,
                liabilities, costs, harms, inconveniences, business disruptions or
                expenditures of any kind that may occur/ arise as a result of or in
                connection with any risk related to transaction. Buyer agrees to release
                and indemnify RiceHouse (and our agents, affiliates, employees) from all
                claims, demands, actions, proceedings, costs, expenses and damages
                (including without limitation any actual, special, incidental or
                consequential damages) arising out of or in connection with any
                transaction.
              </li>
              <li>
                Buyer acknowledges that RiceHouse shall neither be liable&nbsp;nor
                responsible for any actions&nbsp;or inactions of the Buyer nor any
                breach of conditions, representations or warranties of the Products and
                hereby expressly disclaims any and all responsibility and liability in
                that regard. The Buyer shall be solely responsible for obtaining all
                necessary third-party licenses and permissions (if any required under
                applicable law) regarding the right and authority (if required under
                applicable laws) to re-sell, trade, re-distribute or export or offer to
                sell, trade the products or services and such sale, trade, distribution
                or export or offer does not violate any Applicable Laws.
              </li>
            </ol>
          </li>
          <br />
          <li>
            <strong>USER'S RESPONSIBILITIES, REPRESENTATIONS AND WARRANTIES</strong>
          </li>
        </ol>
        <p>You represent, warrant and agree that:</p>
        <ol type="I">
          <li>
            You are a lawfully incorporated business entity and are fully able and
            competent to understand and agree to the Terms;
          </li>
          <li>
            You have full power and authority to accept the Terms, to grant the license
            and authorization (if applicable) and to perform the obligations hereunder;
          </li>
          <li>You will use the Platform and Services for business purposes only;</li>
          <li>
            You will not use or access the Platform for your personal purposes and any
            Products that your purchase shall be for commercial purposes and not for
            personal consumption;
          </li>
          <li>
            the address you provide when registering your account on the Platform is the
            User place of business of your business entity;
          </li>
          <li>
            Your business is validly existing and incorporated / established as per the
            provisions of Applicable Laws;
          </li>
          <li>
            You acknowledge and agree that you are solely responsible for:

            <ol type="i">
              <li>
                obtaining and maintaining all necessary licenses, registrations,
                permits, and authorizations required under the Applicable Laws for the
                purchase, storage, distribution and resale of the Products, as
                applicable;
              </li>
              <li>
                purchasing, storing, distribution, selling, handling, and using the
                Products in compliance with all Applicable Laws including but not
                limited to Food Safety and Standards Authority of India (FSSAI) and the
                Drugs and Cosmetics Act, 1940, etc. (to the extent applicable); and
              </li>
              <li>
                any other Applicable Laws governing the purchase, sale and distribution
                of Products from the Platform;
              </li>
            </ol>
          </li>
          <li>
            You shall be solely responsible for obtaining all necessary third-party
            licenses and permissions (if any required) regarding the User Content
            submitted, posted or displayed;
          </li>
          <li>
            any User Content that you submit, post or display does not infringe or
            violate any of the copyright, patent, trademark, trade name, trade secrets
            or any other personal or proprietary rights of any third party;
          </li>
          <li>
            such information and material whether submitted during the registration
            process or thereafter throughout the continuation of the use of the Platform
            or any Services is true, accurate, current and complete;
          </li>
          <li>
            You will maintain and promptly amend all information and material to keep it
            true, accurate, current and complete;
          </li>
          <li>
            You may be required to promptly furnish additional documents or information
            as and when requested by RiceHouse to continue using and accessing the Platform
            and availing the Services. You agree to promptly provide such additional
            documents and information, failing RiceHouse reserves its right to take
            appropriate measures as set out under Paragraph 7 (Breaches and Suspension)
            of the General Terms; and
          </li>
          <li>
            You consent to the inclusion of the contact information about You in RiceHouse's
            database and usage of the same as per RiceHouse's privacy policy.&nbsp;
          </li>
        </ol>
        <ol start="9">
          <br />
          <li>
            <strong>BREACHES AND SUSPENSION</strong>
          </li>
        </ol>
        <ol type="I">
          <li>
            If any User breaches any Terms, or if RiceHouse has reasonable grounds to
            believe that a User is in breach of any Terms, or could subject RiceHouse or its
            affiliates to liability, or is otherwise found inappropriate or unlawful in
            RiceHouse's opinion, RiceHouse shall have the right to take such disciplinary
            actions as it deems appropriate, including without limitation:
            <ol type="i">
              <li>
                suspending or terminating the User's account and any and all accounts
                determined to be related to such account by RiceHouse in its discretion;
              </li>
              <li>
                blocking, restricting, downgrading, suspending or terminating the
                subscription of, access to, or current or future use of any Service;
              </li>
              <li>
                removing any product listings or User Content that the User has
                submitted, posted or displayed;
              </li>
              <li>withhold settlement of payments by RiceHouse to the User;</li>
              <li>
                any other corrective actions, discipline or penalties as RiceHouse may deem
                necessary or appropriate in its sole discretion.
              </li>
            </ol>
          </li>
          <li>
            RiceHouse does not pre-screen User Content and RiceHouse is under no obligation to
            pre-screen any such content or information. However, RiceHouse may at its
            discretion and/or in accordance with Applicable Law voluntarily take down
            any content or information posted by you on the Platform and if RiceHouse
            determines that any content or information is in violation of these Terms,
            RiceHouse may remove such content or information from the Platform without
            notice. Such actions do not impose any liability on RiceHouse with respect to
            content or information posted, published or transmitted by users on the
            Platform.
          </li>
          <li>
            In the event a User becomes inactive or if no transaction is noticed by
            RiceHouse, in such a case RiceHouse reserves its right to deactivate or suspend a
            User's account in its sole discretion, with or without giving any notice to
            the User.
          </li>
          <li>
            RiceHouse reserves the right to cooperate fully with governmental authorities,
            private investigators, injured third parties in the investigation of any
            suspected criminal or civil wrongdoing and/or any third parties alleging a
            claim against User. Further, RiceHouse may disclose the User's identity and
            contact information, if requested by any third party, government or law
            enforcement body, an injured third party, or as a result of a subpoena or
            other legal action.
          </li>
          <li>
            If it comes to the knowledge of RiceHouse or RiceHouse reasonably believes that any
            User has availed any Services to obtain any Product for its personal use or
            consumption or for any purpose other than a commercial purpose, RiceHouse shall
            have the right in its sole discretion, without intimation to the User, to
            take action such as but not limited to suspending or terminating the User's
            account and any and all accounts determined to be relation to such account.
          </li>
        </ol>
        <ol start="10">
          <br />
          <li>
            <strong>PAYMENTS</strong>
          </li>
        </ol>
        <ol type="I">
          <li>
            Upon placing an Order on the Platform, a Buyer can opt to make payment for
            the Products purchased by using any of the modes of payment provided by us /
            our third-party service providers on the Platform, from time to time.
            However, it is hereby clarified that if the Buyer opts to make payments
            through any such mode made available by us or any third-party engaged by us
            for this purpose then we or the third-party engaged by us for the same shall
            only act in a fiduciary capacity.
          </li>
          <li>
            In connection with processing payments for any Order, your information such
            as name, bank details, and billing address (“<strong>Payment Details</strong>”) 
            may be provided either to RiceHouse or the third-party payment processor. By
            providing the Payment Details, you represent, warrant, and covenant that:
            (i) you are legally authorized to provide such Payment Details; (ii) you are
            legally authorized to perform payments using such Payment Details; and (iii)
            such action does not violate the terms and conditions applicable to your use
            of such Payment Details or Applicable Law. You may add, delete, and edit the
            Payment Details You have provided from time to time through the Platform.
          </li>
          <li>
            If the Buyers are directed to a third-party payment processor from the
            Platform, they may be subject to terms and conditions governing use of that
            third party's service and that third party's personal information collection
            practices. Buyers are requested to review such terms and conditions and
            privacy policy before using such third-party websites. User(s) providing
            billing information, delivery address or other contact information of its
            end user/consumer to RiceHouse or other delivery service provider, shall ensure
            that it has necessary consents and approvals from the respective end
            user/consumer as may be required under Applicable Laws.
          </li>
          <li>
            For enabling payment facility for the Buyer using a credit card, RiceHouse may
            charge a convenience fee&nbsp;(including GST)&nbsp;from the Buyer. Such
            convenience fee&nbsp;(including GST)&nbsp;shall be visible on the payment
            page at the time of checkout and the convenience fee&nbsp;so&nbsp;charged
            shall be subject to change at RiceHouse's sole discretion&nbsp;without any
            further notice. Such convenience fee charged is non-refundable under any
            circumstances.
          </li>
          <li>
            At the time of placing the Order to purchase Products on the Platform, we
            may in our sole discretion require Buyer to pay a token amount equivalent to
            a certain percentage of the value of the Product(s) purchased from RiceHouse
            (<strong>“Token Amount”</strong>). Such Token Amount payable by the Buyer
            shall in no event exceed the transaction amount for an Order. The Token
            Amount shall be non-interest bearing and shall be held in trust by us. This
            Token Amount shall be adjusted from payment received from the Buyer against
            the order delivered. In the event of any cancellation of the Order by the
            Buyer, once the order has been marked ‘ready to ship' or is marked as
            Undelivered Shipment 
            we may in our sole discretion either:

            <ol type="i">
              <li>
                deduct a ‘Cancellation Penalty Fee' and refund the remaining Token
                Amount to the Buyer; or
              </li>
              <li>forfeit the Token Amount as ‘Cancellation Penalty';</li>
            </ol>
            <p>
              You agree and acknowledge that our decision in this regard shall be final
              and binding. If you do not agree to the above, you may choose not to
              transact on the Platform. If you continue to transact on the Platform, it
              shall be deemed that you have agreed and accepted the above terms.
            </p>
          </li>
          <li>
            Buyer acknowledges that it is solely responsible for the transactions /
            payments made to RiceHouse for the Products purchased by the Buyer. We shall be
            entitled to verify any transactions authenticated and/or authorised by the
            Buyer or its payment instructions.
          </li>
          <li>
            In case the Buyer chooses to make the payments to RiceHouse via post-dated
            cheques (if applicable), the Buyer shall ensure that such post-dated cheques
            are duly filled and are in the name of RiceHouse. If such post-dated cheques are
            returned to the Buyer due to incorrect information including but not limited
            to incorrect amount or incorrect date mentioned on the cheque or any other
            reason whatsoever, in such cases, the Buyer, upon our request, shall replace
            such post-dated cheques with duly filled new post-dated cheques or make the
            payment in such other mode as may be communicated to the Buyer, as per the
            discretion of RiceHouse. It is further clarified that in case the Buyer on our
            request, fails to replace the post-dated cheques with duly filled new
            post-dated cheques or fails to make the payment in a timely manner, RiceHouse
            shall reserve the right to take legal action against the Buyer. Further,
            RiceHouse shall have the right in its sole discretion, without intimation to the
            User, to take action such as but not limited to suspending or terminating
            the User's account and any and all accounts determined to be relation to
            such account. The Buyer shall fully indemnify RiceHouse against all claims,
            actions, proceedings and demands including any suits, claims, disputes or
            such differences that are brought against RiceHouse for such failure.
          </li>
          <li>
            We further reserve the right to discontinue the provision of the facility of
            post-dated cheque collection, as per our discretion and without any prior
            intimation.
          </li>
          <li>
            You hereby acknowledge and agree that RiceHouse shall not be liable for failure
            of any transaction undertaken on Platform for any reason whatsoever
            including but not limited to (i) your bank account did not contain
            sufficient funds to complete the transaction; (b) you have not provided the
            RiceHouse with correct Payment Details; (c) your payment card has expired; or
            (d) circumstances beyond the RiceHouse's reasonable control (such as power
            outages, interruptions of cellular service, any technical error or any other
            interferences from an outside force) which prevent the execution of the
            transaction.
          </li>
          <li>
            Buyer shall comply with all the applicable regulations/ laws in relation to
            cash transaction as stipulated under the applicable tax laws.
          </li>
          <li>
            Any refunds shall be subject to the Shipment Policy, Return Shipments Policy
            and
            <a href="https://ricehouse.in/shippingpolicy">Undelivered Shipment Policy</a>. Refunds shall be processed in the same manner as they are received.
            Refund amount will reflect in the Buyer's bank account based on respective
            banks policies.
          </li>
          <li>
            If you avail service from any third party service provider using the
            Platform, upon receipt of instruction from such third party service
            provider, you agree and authorise us to remit and settle such collected
            payments (after deduction of our fees (if any) and any other charges or
            taxes applicable under tax laws) to the designated bank account of the third
            party service provider within such timelines as mentioned in the settlement
            process. You agree and acknowledge that no separate authorisation will be
            required by us to collect and transfer payment to such third-party service
            provider.
          </li>
          <li>
            RiceHouse shall not be responsible for any unauthorised transactions conducted
            on the Platform using Your Payment Details. RiceHouse shall not be obligated to
            refund any money to You in such instances.
          </li>
        </ol>
        <br />
        <ol start="11">
          <li><strong>WARRANTY AND LIABILITY</strong></li>
        </ol>
        <p>
          The Buyer must inspect the Products upon delivery and report any defects or
          non-conformance immediately. If RiceHouse determines that the issue cannot be
          resolved, the Buyer may return the affected Products, subject to RiceHouse's
          approval and return policies.
        </p>
        <p>
          We do not provide any warranties, whether express or implied, including but
          not limited to warranties of merchantability, quality, fitness for a
          particular purpose, or durability. To the maximum extent permitted by law, we
          shall not be liable for any direct, indirect, incidental, or consequential
          damages arising from the use or purchase of the Products.
        </p>
        <ol start="12">
          <li>
            <strong>DELIVERY </strong>
          </li>
          <ol type="I">
            <li>
              We reserve the right to engage the services of third-party service
              providers to deliver the Products to you. It is hereby clarified that so
              far as the collection of payments are concerned, such third party shall
              act in a fiduciary capacity solely for the purposes of collection of
              payment from you.
            </li>
            <li>
              Upon receipt of Order, we will use our best endeavours to deliver the
              Products to the User to the delivery address and designated recipient in
              the Delivery Note. For the avoidance of doubt, the designated recipient
              may not be the Buyer. We will not verify the identity of the person
              receiving the Shipment at the designated delivery address, however, we
              will obtain the signature of recipient of the Shipment on the Delivery
              Note. The Buyer hereby authorises us to contact the Buyer, at any given
              point of time, by way of calls or SMS or any other method of messaging
              (Example: WhatsApp) for transactional purposes including but not limited
              to order confirmations and/or delivering the Order(s). RiceHouse will not be
              responsible for any delay in delivering the order placed by you on the
              Platform caused due to the incorrect or incomplete address provided by
              you.
            </li>
            <li>
              At the time of placing the Order, if the Buyer chooses the option, pay
              ‘cash on delivery', we will collect the amount pertaining to the
              Order at the time of delivery of the Products to the Consignee. It is
              further clarified that if such payments are collected by a third-party
              service provider, then such third party shall act in a fiduciary capacity
              solely for the purposes of collection of payment from you.
            </li>
            <li>
              Consignee(s) are required to behave properly with the pickup and delivery
              associates of RiceHouse. Any misbehaviour, unprofessional conduct, verbal and
              physical abuse is prohibited and will be considered as a violation of
              these Terms. RiceHouse reserves the right to suspend your use or access to the
              Platform in its sole discretion if deemed that a Buyer is in violation of
              this clause.
            </li>
            <li>
              Every effort will be made to adhere to the delivery schedule, however, the
              Shipment may be delayed due to circumstances beyond our reasonable control
              or due to any force majeure event.
            </li>
            <li>
              Further, you agree to be bound by the provisions of the Shipment Policy
              which can be accessed
              <a href="https://ricehouse.in/shippingpolicy">here</a>.
            </li>
          </ol>
          <br />
          <li><strong>UNDELIVERED SHIPMENT</strong></li>
          <p>
            You acknowledge that a delivery failure may occur for various reasons, as
            set out under the Undelivered Shipment Policy. In relation to the
            Undelivered Shipments (as defined under the Undelivered Shipment Policy),
            you agree to be bound by the provisions of the Undelivered Shipment Policy
            which can be accessed
            <a href="https://ricehouse.in/shippingpolicy">here</a>.
          </p>
          <li><strong>RETURNS</strong></li>
          <p>
            In case of any Return Request (as defined under the Return Shipment Policy),
            you agree to be bound by the provisions of the Return Shipment Policy which
            can be accessed
            <a href="https://ricehouse.in/returnpolicy">here</a>.
          </p>
          <li><strong>SALE IN INDIA ONLY</strong></li>
          <p>
            Unless otherwise specified, the Products on the Platform are presented
            solely for the purpose of sale in India. RiceHouse makes no representation that
            the material on the Platform is appropriate or available for use in other
            locations/ countries other than India. Those who choose to access the
            Platform from other locations/ countries other than India do so on their own
            initiative and RiceHouse is not responsible for supply of Products/ refund for
            the Products ordered from other locations/ countries other than India and
            compliance with local laws, if and to the extent local laws are applicable.
          </p>
          <li><strong>DATA PROTECTION </strong></li>
          <p>
            Personal information supplied by User(s) during the use of the Platform is
            governed by RiceHouse's privacy policy which can found
            <a href="https://ricehouse.in/privacypolicy">here</a>.
          </p>
          <li>
            <strong>LIMITATION OF LIABILITY AND INDEMNITY</strong>
            <ol type="I">
              <li>
                To the maximum extent permitted by law, the Services provided by RiceHouse
                on or through the Platform are provided “as is”, “as available”
                and&nbsp;“with all faults”, and RiceHouse hereby expressly disclaims any and
                all warranties, express or implied, including but not limited to, any
                warranties of condition, quality, durability, performance, accuracy,
                reliability, merchantability or fitness for a particular purpose. All
                such warranties, representations, conditions, and undertakings are
                hereby excluded.
              </li>
              <li>
                RiceHouse procures Products from third-party vendors and offers them on the
                Platform. RiceHouse has endeavored to ensure that all the information on the
                Platform is accurate. However, RiceHouse makes no representations or
                warranties about the validity, accuracy, correctness, reliability,
                quality, stability, completeness or accurateness of any information
                provided on or through the Platform; RiceHouse does not represent or warrant
                that the manufacture, importation, export, distribution, offer, display,
                purchase and/or use of Products or Services offered or displayed on the
                Platform does not violate any third party rights; and RiceHouse makes no
                representations or warranties of any kind concerning any product or
                service offered or displayed on the Platform. Except as provided herein,
                to the fullest extent permissible by Applicable Law, the aggregate
                liability of RiceHouse for any claims that may arise in connection with
                these Terms shall not exceed an amount of INR 1000/-.
              </li>
              <li>
                Under no circumstances will RiceHouse be liable for any consequential,
                incidental, special, exemplary or punitive damages, including but not
                limited to any lost profits that result from your purchase of any
                products on platform or any services availed, even if RiceHouse has been
                advised of the possibility of such damages.&nbsp;
              </li>
            </ol>
          </li>
          <br />
          <li><strong>FORCE MAJEURE</strong></li>
          <p>
            Under no circumstances shall RiceHouse be held liable for any losses, delay or
            failure or disruption of the Platform Content or Services delivered through
            the Platform resulting directly or indirectly from acts of nature, forces or
            causes beyond our reasonable control, including without limitation, internet
            failures, computer, telecommunications or any other equipment failures,
            electrical power failures, strikes, labor disputes, riots, insurrections,
            civil disturbances, shortages of labor or materials, fires, flood, storms,
            explosions, acts of God, war, governmental actions, epidemics, pandemics,
            curfews, lock-down, orders of domestic or foreign courts or tribunals or
            non-performance of third parties.
          </p>
          <li>
            <strong>INTELLECTUAL PROPERTY RIGHTS</strong>
            <ol type="I">
              <li>
                RiceHouse is the sole owner or lawful licensee of all the rights and
                interests in the Platform and the Platform Content. All title, ownership
                and intellectual property rights in the Platform and Platform Content
                shall remain with RiceHouse or licensors of the Platform Content, as the
                case may be. All rights not otherwise claimed under the Terms or by
                RiceHouse are hereby reserved.
              </li>
              <li>
                “RiceHouse” and any other related icons and logos are registered trademarks
                of RH, in various jurisdictions and are protected under applicable
                copyright, trademark and other proprietary rights laws. The unauthorized
                copying, modification, use or publication of these marks is strictly
                prohibited.&nbsp;
              </li>
              <li>
                RiceHouse may, at its sole discretion, permit the User(s) of the Platform,
                in writing, to use “RiceHouse” and any other related icons and logos for
                indicative purposes in the form and manner and terms and conditions as
                maybe agreed by RiceHouse.
              </li>
              <li>
                You shall be solely responsible for User Content posted or transmitted
                on the Platform and shall indemnify RiceHouse against any claim or liability
                arising from any User Content or information posted or transmitted by
                You on the Platform.
              </li>
              <li>
                You grant us non-exclusive, worldwide, perpetual, royalty free and
                transferable license to use, modify, adapt, enhance, refine, transform,
                and create derivative works of such User Content, including but not
                limited to the use of generative AI technologies, tools, or services.
                This license includes, but is not limited to, the right to use, modify,
                enhance, or create derivative works of the User Content for any purpose,
                including, without limitation, promotional, advertising, and marketing
                purposes, across any media, whether now known or hereafter devised. We
                shall be entitled to use the User Content, consistent with our Privacy
                Policy and these Terms as adopted in accordance with Applicable Laws.
                You are not entitled to any payment or compensation for such usage.
              </li>
            </ol>
          </li>
          <br />
          <li>
            <strong>NOTICES</strong>
            <ol type="I">
              <li>
                All legal notices or demands to or upon RiceHouse shall be made in writing
                and sent to RiceHouse personally, by courier, certified mail, or facsimile
                to the following entity and address: 12/2-66, krishanappa layout, R. R. Nagar, Kerekodi Main Rd, Hosakerehalli, Bengaluru, Karnataka 560085, India, Attn: Legal
                Department. The notices shall be effective when they are received by
                RiceHouse in any of the above-mentioned manner.
              </li>
              <li>
                All legal notices or demands to or upon a User shall be effective if
                either delivered personally, sent by courier, certified mail, by
                facsimile or email to the last-known correspondence, fax or email
                address provided by the User to RiceHouse, or SMS, WhatsApp messages, or
                in-app notifications, or by posting such notice or demand on an area of
                the Platform that is publicly accessible without a charge or through
                such other mode of communication as RiceHouse may deem fit in its
                discretion. Notice to a User shall be deemed to be received by such User
                if and when, a) RiceHouse is able to demonstrate that communication, whether
                in physical or electronic form, has been sent to such User, or b)
                immediately upon RiceHouse posting such notice on an area of the Platform
                that is accessible by the User or publicly accessible without charge.
              </li>
            </ol>
          </li>
          <br />
          <li>
            <strong>MISCELLANEOUS PROVISIONS</strong>
            <ol type="I">
              <li>
                Unless otherwise communicated to you by RiceHouse, the Terms constitute the
                entire agreement between User and RiceHouse and govern the User's use of the
                Platform and any of the Services. The Terms shall supersede any prior
                written or oral agreements that you may have had in relation to the use
                of the Platform and any of the Services.
              </li>
              <li>
                Unless stated otherwise, we will be your one stop solution for all the
                services (except credit) on the Platform with effect from 00:00 hours on
                7<sup>th</sup> April 2025 (“Cut-Off Date”), and any new transactions on
                the Platform shall be governed by these Terms. It is clarified that, any
                transaction made by you on the Platform before the Cut-Off
                Date&nbsp;shall be governed by your arrangements with the relevant
                parties (i.e., third party service providers) as existing prior to the
                Cut Off Date. The erstwhile terms of use are available here.
              </li>
              <li>
                RiceHouse and User are independent contractors, and no agency, partnership,
                joint venture, employee-employer relationship is intended or created by
                the Terms. The relationship between you and us is one of independent
                contractors, and nothing contained in these Terms will be construed to
                (a) give either party the power to direct and control the day-to-day
                activities of the other, (b) constitute the parties as partners, joint
                ventures, co-owners or otherwise as participants in a joint or common
                undertaking, or (c) allow you to create or assume any obligation on our
                behalf for any purpose whatsoever.
              </li>
              <li>
                If any provision of the Terms is held to be invalid or unenforceable,
                such provision shall be deleted and the remaining provisions shall
                remain valid and be enforced.
              </li>
              <li>
                RiceHouse's failure to enforce any right or failure to act with respect to
                any breach by User under the Terms will not constitute a waiver of that
                right nor a waiver of RiceHouse's right to act with respect to subsequent or
                similar breaches.
              </li>
              <li>
                RiceHouse shall have the right to assign the Terms (including all of our
                rights, titles, benefits, interests, and obligations and duties in the
                Terms to any person or entity (including any affiliates of RiceHouse). User
                may not assign, in whole or part, the Terms to any third party or
                person.
              </li>
              <li>
                The Terms shall be governed by the laws of India and the parties to the
                Terms agree to submit to the exclusive jurisdiction of the courts of
                Bangalore, Karnataka, India.
              </li>
            </ol>
          </li>
        </ol>
      </div>
    <ContactUsSection />
    </div>
  )
}

export default TandC